/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AppRouteImport } from './pages/_app'
import { Route as AuthRouteImport } from './pages/_auth'
import { Route as ResetPasswordRouteImport } from './pages/reset-password'
import { Route as VerifyEmailRouteImport } from './pages/verify-email'
import { Route as AppDashboardRouteImport } from './pages/_app/dashboard'
import { Route as AppNotificationsRouteImport } from './pages/_app/notifications'
import { Route as AppProfileRouteImport } from './pages/_app/profile'
import { Route as AuthForgotPasswordRouteImport } from './pages/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './pages/_auth/login'
import { Route as AuthRegisterRouteImport } from './pages/_auth/register'
import { Route as AuthCallbackRouteImport } from './pages/auth/callback'
import { Route as InvitationsAcceptRouteImport } from './pages/invitations/accept'
import { Route as AppTenantsIndexRouteImport } from './pages/_app/tenants/index'
import { Route as AppTenantsSlugRouteImport } from './pages/_app/tenants/$slug'
import { Route as AppTenantsSlugIndexRouteImport } from './pages/_app/tenants/$slug.index'
import { Route as AppTenantsSlugMembersRouteImport } from './pages/_app/tenants/$slug.members'
import { Route as AppTenantsSlugSettingsRouteImport } from './pages/_app/tenants/$slug.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantsIndexRoute = AppTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsSlugRoute = AppTenantsSlugRouteImport.update({
  id: '/tenants/$slug',
  path: '/tenants/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsSlugIndexRoute = AppTenantsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantsSlugRoute,
} as any)
const AppTenantsSlugMembersRoute = AppTenantsSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppTenantsSlugRoute,
} as any)
const AppTenantsSlugSettingsRoute = AppTenantsSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTenantsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/tenants/$slug': typeof AppTenantsSlugRouteWithChildren
  '/tenants/': typeof AppTenantsIndexRoute
  '/tenants/$slug/members': typeof AppTenantsSlugMembersRoute
  '/tenants/$slug/settings': typeof AppTenantsSlugSettingsRoute
  '/tenants/$slug/': typeof AppTenantsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/tenants': typeof AppTenantsIndexRoute
  '/tenants/$slug/members': typeof AppTenantsSlugMembersRoute
  '/tenants/$slug/settings': typeof AppTenantsSlugSettingsRoute
  '/tenants/$slug': typeof AppTenantsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/_app/tenants/$slug': typeof AppTenantsSlugRouteWithChildren
  '/_app/tenants/': typeof AppTenantsIndexRoute
  '/_app/tenants/$slug/members': typeof AppTenantsSlugMembersRoute
  '/_app/tenants/$slug/settings': typeof AppTenantsSlugSettingsRoute
  '/_app/tenants/$slug/': typeof AppTenantsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/auth/callback'
    | '/invitations/accept'
    | '/tenants/$slug'
    | '/tenants/'
    | '/tenants/$slug/members'
    | '/tenants/$slug/settings'
    | '/tenants/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/auth/callback'
    | '/invitations/accept'
    | '/tenants'
    | '/tenants/$slug/members'
    | '/tenants/$slug/settings'
    | '/tenants/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/reset-password'
    | '/verify-email'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/auth/callback'
    | '/invitations/accept'
    | '/_app/tenants/$slug'
    | '/_app/tenants/'
    | '/_app/tenants/$slug/members'
    | '/_app/tenants/$slug/settings'
    | '/_app/tenants/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tenants/': {
      id: '/_app/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AppTenantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/$slug': {
      id: '/_app/tenants/$slug'
      path: '/tenants/$slug'
      fullPath: '/tenants/$slug'
      preLoaderRoute: typeof AppTenantsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/$slug/': {
      id: '/_app/tenants/$slug/'
      path: '/'
      fullPath: '/tenants/$slug/'
      preLoaderRoute: typeof AppTenantsSlugIndexRouteImport
      parentRoute: typeof AppTenantsSlugRoute
    }
    '/_app/tenants/$slug/members': {
      id: '/_app/tenants/$slug/members'
      path: '/members'
      fullPath: '/tenants/$slug/members'
      preLoaderRoute: typeof AppTenantsSlugMembersRouteImport
      parentRoute: typeof AppTenantsSlugRoute
    }
    '/_app/tenants/$slug/settings': {
      id: '/_app/tenants/$slug/settings'
      path: '/settings'
      fullPath: '/tenants/$slug/settings'
      preLoaderRoute: typeof AppTenantsSlugSettingsRouteImport
      parentRoute: typeof AppTenantsSlugRoute
    }
  }
}

interface AppTenantsSlugRouteChildren {
  AppTenantsSlugMembersRoute: typeof AppTenantsSlugMembersRoute
  AppTenantsSlugSettingsRoute: typeof AppTenantsSlugSettingsRoute
  AppTenantsSlugIndexRoute: typeof AppTenantsSlugIndexRoute
}

const AppTenantsSlugRouteChildren: AppTenantsSlugRouteChildren = {
  AppTenantsSlugMembersRoute: AppTenantsSlugMembersRoute,
  AppTenantsSlugSettingsRoute: AppTenantsSlugSettingsRoute,
  AppTenantsSlugIndexRoute: AppTenantsSlugIndexRoute,
}

const AppTenantsSlugRouteWithChildren = AppTenantsSlugRoute._addFileChildren(
  AppTenantsSlugRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTenantsSlugRoute: typeof AppTenantsSlugRouteWithChildren
  AppTenantsIndexRoute: typeof AppTenantsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppTenantsSlugRoute: AppTenantsSlugRouteWithChildren,
  AppTenantsIndexRoute: AppTenantsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
